# Generated by Django 5.1.2 on 2024-11-02 00:25

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("posologie", models.TextField()),
                ("heure_de_prise", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Medecin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=70)),
                (
                    "numero",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=70)),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse mail"),
                ),
                ("age", models.CharField(max_length=50)),
                (
                    "genre",
                    models.CharField(
                        choices=[("F", "Femme"), ("M", "Homme")],
                        max_length=50,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "hypertention",
                    models.CharField(
                        choices=[("oui", "Oui"), ("non", "Non")],
                        max_length=50,
                        verbose_name="Hypertention",
                    ),
                ),
                (
                    "maladie_cardiaque",
                    models.CharField(
                        choices=[("oui", "Oui"), ("non", "Non")],
                        max_length=50,
                        verbose_name="Maladie Cardiaque",
                    ),
                ),
                (
                    "numero",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("masse", models.FloatField()),
                ("taille", models.FloatField()),
                ("imc", models.FloatField(blank=True, null=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("N", "Normale"),
                            ("I", "Intermediaire"),
                            ("U", "Urgent"),
                        ],
                        max_length=50,
                        verbose_name="Etat",
                    ),
                ),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="diabete_predict.medecin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ordonance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date_emission", models.DateField(auto_now_add=True)),
                ("date_validite", models.DateField()),
                (
                    "medicaments",
                    models.ManyToManyField(to="diabete_predict.medicament"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordonances",
                        to="diabete_predict.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RendezVous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heure", models.TimeField()),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="diabete_predict.medecin",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="diabete_predict.patient",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "heure", "patient", "medecin")},
            },
        ),
    ]
