# Generated by Django 5.1.2 on 2024-11-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diabete_predict", "0003_ordonance_date_emition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordonance",
            name="date_emition",
        ),
    ]
